version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tamagitto-postgres
    environment:
      POSTGRES_USER: tamagitto
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: tamagitto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tamagitto -d tamagitto"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tamagitto-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ../backend
      dockerfile: ../infrastructure/Dockerfile
    container_name: tamagitto-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tamagitto:${POSTGRES_PASSWORD:-password}@postgres:5432/tamagitto
      - REDIS_URL=redis://redis:6379
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS:-["http://localhost:3000"]}
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8000}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ../backend:/app
    command: ["uv", "run", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  caddy:
    image: caddy:2-alpine
    container_name: tamagitto-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../static-site:/var/www/static:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    environment:
      - DOMAIN=${DOMAIN:-localhost}

volumes:
  postgres_data:
  redis_data:  
  caddy_data:
  caddy_config:

networks:
  default:
    name: tamagitto-network